controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

Register:
    path: /api/register
    controller: App\Controller\AuthController\RegisterController::register
    methods: POST

verifyEmail:
    path: /api/verifyEmail
    controller: App\Controller\AuthController\VerifyMailControllers\VerifyMailController::verify
    methods: POST

Login:
    path: /api/login
    controller: App\Controller\LoginController::login
    methods: POST

gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    controller: App\Controller\AuthController\RefreshTokenControllers\RefreshTokenController::refresh
    methods: [POST]

SendMessage:
    path: /api/send/message
    controller: App\Controller\MessagesController\SendMessage::sendMes
    methods: POST

GetMessages:
    path: /api/get/messages
    controller: App\Controller\MessagesController\GetMessages::get
    methods: GET

ChangeName:
    path: /api/change/name
    controller: App\Controller\AuthController\ChangeNameController::changeName
    methods: POST

ChangeMessages:
    path: /api/change/messages
    controller: App\Controller\MessagesController\ChangeMessageController::changeMess
    methods: POST

DeleteMessages:
    path: /api/delete/message
    controller: App\Controller\MessagesController\DeleteMessagesController::deleteMess
    methods: POST

ResetPasswordSend:
    path: /api/reset/password/send
    controller: App\Controller\AuthController\ResetPasswordController\ResetPasswordSendController::resetPassSend
    methods: POST

ResetPasswordResert:
    path: /api/reset/password/reset
    controller: App\Controller\AuthController\ResetPasswordController\ResetPasswordController::reset
    methods: POST

Api_logout:
    path: /api/logout
    controller: App\Controller\Logout\LogoutController::logout
    methods: GET


CreateGroup:
    path: /api/create/group
    controller: App\Controller\GroupController\createGroupController::createGroup
    methods: POST

FollowGroup:
    path: /api/follow{id}
    controller: App\Controller\GroupController\FollowGroupController::follow
    methods: POST
