controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute



Register:
    path: api/register
    controller: App\Controller\RegisterController::register
    methods: POST

veryfiEmail:
    path: /api/veryfiEmail
    controller: App\Controller\VeryfiMailController::veryfi
    methods: POST


Login:
    path: /api/login
    controller: App\Controller\LoginController::login
    methods: POST

gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken.refresh
    methods: [POST]



test:
    path: /api/tests
    controller: App\Controller\TestService::test
    methods: POST


