controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

Register:
    path: /api/register
    controller: App\Controller\RegistrationController\RegisterController::register
    methods: POST

verifyEmail:
    path: /api/verifyEmail
    controller: App\Controller\VerifyMailControllers\VerifyMailController::verify
    methods: POST

Login:
    path: /api/login
    controller: App\Controller\LoginController::login
    methods: POST

gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    controller: App\Controller\RefreshTokenController::refresh
    methods: [POST]

SendMessage:
    path: /api/send/message
    controller: App\Controller\SendMessagesControllers\SendMessage::sendMes
    methods: POST

GetMessages:
    path: /api/get/messages
    controller: App\Controller\QueryControllers\GetMessages::get
    methods: GET

ChangeName:
    path: /api/change/name
    controller: App\Controller\ChangeController\ChangeNameController::changeName
    methods: POST

ChangeMessages:
    path: /api/change/messages
    controller: App\Controller\ChangeController\ChangeMessageController::changeMess
    methods: POST

DeleteMessages:
    path: /api/delete/message
    controller: App\Controller\DeleteController\DeleteMessagesController::deleteMess
    methods: POST

ResetPasswordSend:
    path: /api/reset/password/send
    controller: App\Controller\ResetPasswordController\ResetPasswordSendController::resetPassSend
    methods: POST

ResetPasswordResert:
    path: /api/reset/password/reset
    controller: App\Controller\ResetPasswordController\ResetPasswordController::reset
    methods: POST

Api_logout:
    path: /api/logout
    controller: App\Controller\Logout\LogoutController::logout
    methods: GET


CreateGroup:
    path: /api/create/group
    controller: App\Controller\Create\createGroupController::createGroup
    methods: POST

