controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute



Register:
    path: api/register
    controller: App\Controller\RegisterController::register
    methods: POST



veryfiEmail:
    path: /api/veryfiEmail
    controller: App\Controller\VeryfiMailController::veryfi
    methods: POST

TestMailer:
    path: api/test/mailer
    controller: App/Controller/MailerTest::test



Login:
    path: /api/login
    controller: App\Controller\LoginController::login
    methods: POST


