controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

Register:
    path: /api/register
    controller: App\Controller\Registeration\RegisterController::register
    methods: POST

verifyEmail:
    path: /api/verifyEmail
    controller: App\Controller\VerifyMailController::verify
    methods: POST

Login:
    path: /api/login
    controller: App\Controller\LoginController::login
    methods: POST

gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    controller: App\Controller\RefreshTokenController::refresh
    methods: [POST]

SendMessage:
    path: /api/send/message
    controller: App\Controller\SendMessage::sendMes
    methods: POST

GetMessages:
    path: /api/getMessages
    controller: App\Controller\GetMessages::get
    methods: POST

ChangeName:
    path: /api/change/name
    controller: App\Controller\Change\ChangeNameController::changeName
    methods: POST

ChangeMessages:
    path: /api/change/messages
    controller: App\Controller\Change\ChangeMessageController::changeMess
    methods: POST

DeleteMessages:
    path: /api/delete/message
    controller: App\Controller\Delete\DeleteMessagesController::deleteMess
    methods: POST

ResetPasswordSend:
    path: /api/reset/password/send
    controller: App\Controller\Reset\ResetPasswordSendController::resetPassSend
    methods: POST

ResetPasswordResert:
    path: /api/reset/password/reset
    controller: App\Controller\Reset\ResetPasswordController::reset
    methods: POST