controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

Register:
    path: /api/register
    controller: App\Controller\AuthController\RegisterController::register
    methods: POST

verifyEmail:
    path: /api/verifyEmail
    controller: App\Controller\AuthController\VerifyMailControllers\VerifyMailController::verify
    methods: POST

Login:
    path: /api/login
    controller: App\Controller\LoginController::login
    methods: POST

gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    controller: App\Controller\AuthController\RefreshTokenControllers\RefreshTokenController::refresh
    methods: [POST]

SendMessage:
    path: /api/messages{id}
    controller: App\Controller\MessagesController\MessagesController::sendMessages
    methods: POST

GetMessages:
    path: /api/messages
    controller: App\Controller\MessagesController\MessagesController::getMessages
    methods: GET

ChangeName:
    path: /api/name
    controller: App\Controller\AuthController\ChangeNameController::changeName
    methods: PUT

ChangeMessages:
    path: /api/messages{id}
    controller: App\Controller\MessagesController\MessagesController::changeMessages
    methods: PUT

DeleteMessages:
    path: /api/messages{id}
    controller: App\Controller\MessagesController\MessagesController::deleteMessages
    methods: DELETE

ResetPasswordSend:
    path: /api/reset/password/send
    controller: App\Controller\AuthController\ResetPasswordController\ResetPasswordControllers::resetPasswordSendCodeFun
    methods: POST

ResetPasswordResert:
    path: /api/reset/password
    controller: App\Controller\AuthController\ResetPasswordController\ResetPasswordControllers::resetPasswordCheckCodeFunction
    methods: POST

Api_logout:
    path: /api/logout
    controller: App\Controller\Logout\LogoutController::logout
    methods: GET


CreateGroup:
    path: /api/create/group
    controller: App\Controller\GroupController\createGroupController::createGroup
    methods: POST

FollowGroup:
    path: /api/follow{id}
    controller: App\Controller\GroupController\FollowGroupController::follow
    methods: POST
